USE master;
GO

--Database Master Key
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'myP@%5w0rd';
GO

CREATE CERTIFICATE SqlNug1Cert
WITH SUBJECT = 'TDE Cert'
GO

USE NuggetlabDB
GO
--Database Encryption Key
CREATE DATABASE ENCRYPTION KEY WITH ALGORITHM = AES_256 ENCRYPTION BY SERVER CERTIFICATE SqlNug1Cert
GO

ALTER DATABASE NuggetlabDB
SET ENCRYPTION ON
GO

--BACKUP OPERATIONS
USE master;
GO

BACKUP SERVICE MASTER KEY 
TO FILE = 'C:\SQLNUG.smk'
ENCRYPTION BY PASSWORD = 'SMKmyP@%5w0rd'
GO


BACKUP MASTER KEY
TO FILE = 'C:\DBMK.dmk'
ENCRYPTION BY PASSWORD = 'DMKmyP@%5w0rd'
GO

BACKUP CERTIFICATE SqlNug1Cert
TO FILE = 'C:\CertDEK.dek'
WITH PRIVATE KEY (
    FILE = 'C:\DEKkey.key',
    ENCRYPTION BY PASSWORD = 'CERTmyP@%5w0rd'
)


--RESTORE
CREATE CERTIFICATE SqlNug1Cert
FROM FILE = 'C:\CertDEK.dek'
WITH PRIVATE KEY (
    FILE = 'C:\DEKkey.key',
    DECRYPTION BY PASSWORD = 'CERTmyP@%5w0rd'
)