USE nuggetlabDB
GO

CREATE ROLE devTeam AUTHORIZATION db_securityadmin;
GO

ALTER ROLE devTeam
ADD MEMBER [nuggetlan\DBAs]
GO
GRANT CREATE TABLE TO devTeam
GRANT CREATE PROCEDURE TO devTeam
GRANT CREATE FUNCTION TO devTeam
GRANT CREATE TYPE TO devTeam
GRANT EXECUTE TO devTeam
GO