USE master
GO

CREATE SERVER ROLE ServerTeam
GO
ALTER Server ROLE ServerTeam
  ADD MEMBER [nuggetlab\Administrator]
GO

GRANT CONNECT SQL TO ServerTeam
GRANT VIEW ANY DATABASE TO ServerTeam
GRANT VIEW SERVER STATE TO ServerTeam
GRANT ALTER SERVER STATE TO ServerTeam
GRANT ALTER SETTINGS TO ServerTeam
GRANT SHUTDOWN TO ServerTeam
GO